apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: well-known
  namespace: istio-system
spec:
  hosts:
  - '*'
  gateways:
  - kubeflow-gateway
  http:
  - match:
    - uri:
        prefix: /.well-known/
    route:
    - destination:
        port:
          number: 8089
        host: 10.254.19.15
